# 工作流名称
name: copytest  Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main_" ]
  pull_request:
    branches: [ "main_" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        #skopeo copy docker://redis:7.0.0 docker://registry.cn-hangzhou.aliyuncs.com/liccopen/redis:7.0.0
        #skopeo copy docker://gcr.io/kaniko-project/executor:v1.13.0 docker://registry.cn-hangzhou.aliyuncs.com/liccopen/kaniko-executor:v1.13.0
        #skopeo copy docker://mysql:5.7 docker://registry.cn-hangzhou.aliyuncs.com/liccopen/mysql:5.7
        #skopeo copy docker://emqx:5.1 docker://registry.cn-hangzhou.aliyuncs.com/liccopen/emqx:5.1
        #skopeo copy docker://openjdk:8-jre docker://registry.cn-hangzhou.aliyuncs.com/liccopen/openjdk:8-jre
        #skopeo copy docker://nginx:stable docker://registry.cn-hangzhou.aliyuncs.com/liccopen/nginx:stable
        #skopeo copy docker://tdengine/tdengine:2.6.0.12 docker://registry.cn-hangzhou.aliyuncs.com/liccopen/tdengine:2.6.0.12
        #skopeo copy docker://zlmediakit/zlmediakit:master docker://registry.cn-hangzhou.aliyuncs.com/liccopen/zlmediakit:master

        #skopeo copy docker://discourse/base:release docker://registry.cn-hangzhou.aliyuncs.com/liccopen/discourse_base:latest
        skopeo copy docker://hlohaus789/g4f   docker://registry.cn-hangzhou.aliyuncs.com/hlohaus789/g4f:latest
